### ISSUE TITLE
Text alignment in IE11

### ISSUE THREAD

**Issue by willw-git** [vijithassar/d3textwrap#2] opened 2014-05-21 10:28 UTC
IE 11 textwrap displaces successive wrapped lines outdented to the left. 

Using FireFox to display the D3 graph produces this:
![firefox](https://cloud.githubusercontent.com/assets/1162998/3038771/338f595a-e0d2-11e3-93ed-79a65b3bd858.PNG)
(the red rectangle is the bounding one supplied to d3textwrap).
whereas IE11 with the same code produces this:
![ie_padding 3](https://cloud.githubusercontent.com/assets/1162998/3038773/45e53d0e-e0d2-11e3-99cc-b7500bd6a220.PNG)
It seems to be miscalculating (overestimating) the text width on successive lines.

**Comment by vijithassar** [comment] 2015-02-27 22:25
I still haven't been able to reproduce this myself, so I'm going to close this issue. Thanks for the feedback though! If you have some sample code that reliably reproduces this problem and it isn't because of Bootstrap, please feel free to drop a comment in here and I'll be happy to reopen it and take a look.

**Closed by vijithassar** 2015-02-27 22:25 UTC
